/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author usuario
 */
public class Reproductor extends javax.swing.JFrame implements Observer {

   /**
    * Creates new form Reproductor
    */
   public Reproductor() {
      initComponents();
      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        musicData = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        myBox = new javax.swing.JComboBox<>();
        nextBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();
        prevBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        othersBox = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        musicData.setColumns(20);
        musicData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        musicData.setRows(5);
        jScrollPane1.setViewportView(musicData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 200, 350, 180);

        jLabel1.setFont(new java.awt.Font("Novae", 1, 15)); // NOI18N
        jLabel1.setText("Reproduciendo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 160, 130, 40);

        jLabel6.setFont(new java.awt.Font("Novae", 1, 15)); // NOI18N
        jLabel6.setText("Mi Lista");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 70, 80, 40);

        myBox.setBackground(new java.awt.Color(0, 0, 0));
        myBox.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        myBox.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(myBox);
        myBox.setBounds(400, 120, 295, 40);

        nextBtn.setBackground(new java.awt.Color(255, 255, 255));
        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/fastforward.png"))); // NOI18N
        getContentPane().add(nextBtn);
        nextBtn.setBounds(280, 120, 60, 50);

        playBtn.setBackground(new java.awt.Color(255, 255, 255));
        playBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/play.png"))); // NOI18N
        getContentPane().add(playBtn);
        playBtn.setBounds(150, 100, 100, 80);

        prevBtn.setBackground(new java.awt.Color(255, 255, 255));
        prevBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/backwards.png"))); // NOI18N
        prevBtn.setEnabled(false);
        getContentPane().add(prevBtn);
        prevBtn.setBounds(50, 120, 60, 50);

        removeBtn.setBackground(new java.awt.Color(255, 255, 255));
        removeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        removeBtn.setText("REMOVER DE MI LISTA");
        getContentPane().add(removeBtn);
        removeBtn.setBounds(50, 190, 295, 29);

        jLabel3.setFont(new java.awt.Font("Novae", 1, 15)); // NOI18N
        jLabel3.setText("Toda la musica");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 270, 190, 30);

        othersBox.setBackground(new java.awt.Color(0, 0, 0));
        othersBox.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        othersBox.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(othersBox);
        othersBox.setBounds(50, 300, 295, 40);

        addBtn.setBackground(new java.awt.Color(134, 105, 134));
        addBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addBtn.setText("AÑADIR A MI LISTA");
        getContentPane().add(addBtn);
        addBtn.setBounds(80, 360, 230, 40);

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/exitbutton11.png"))); // NOI18N
        exitBtn.setBorderPainted(false);
        exitBtn.setContentAreaFilled(false);
        getContentPane().add(exitBtn);
        exitBtn.setBounds(760, 400, 40, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/vapor_silk_2x.gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Reproductor().setVisible(true);
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addBtn;
    public javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea musicData;
    public javax.swing.JComboBox<String> myBox;
    public javax.swing.JButton nextBtn;
    public javax.swing.JComboBox<String> othersBox;
    public javax.swing.JButton playBtn;
    public javax.swing.JButton prevBtn;
    public javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables

   @Override
   public void update(Observable o, Object o1){
      
   }

}
